//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BK_VPDKDatDai
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LUAT
    {
        public decimal ID { get; set; }
        public string TIEU_DE { get; set; }
        public Nullable<decimal> ID_CHA { get; set; }
        public string NOI_DUNG { get; set; }
        public string THU_TU_HIEN_THI { get; set; }
    }
}
