//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BK_VPDKDatDai
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HO_SO
    {
        public long IDU { get; set; }
        public long ID { get; set; }
        public Nullable<int> IDSoTiepNhan { get; set; }
        public Nullable<int> IDDM_ThuTucHanhChinh { get; set; }
        public string DM_ThuTucHanhChinh { get; set; }
        public string VeViec { get; set; }
        public string SoBienNhan { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
        public Nullable<int> SoNgayGiaiQuyet { get; set; }
        public Nullable<int> SoNgayLamThue { get; set; }
        public Nullable<System.DateTime> NgayHenTraTBT { get; set; }
        public Nullable<System.DateTime> NgayHenTra { get; set; }
        public string IDDM_District { get; set; }
        public string DM_District { get; set; }
        public string IDDM_Guild { get; set; }
        public string DM_Guild { get; set; }
        public string DiaChiChiTiet { get; set; }
        public string TenNguoiNop { get; set; }
        public string CMTNguoiNop { get; set; }
        public string DiaChiNguoiNop { get; set; }
        public string DienThoaiNguoiNop { get; set; }
        public string MailNguoiNop { get; set; }
        public string GioiTinhNguoiNop { get; set; }
        public Nullable<int> IDChuSoHuu { get; set; }
        public string TenChuSoHuu { get; set; }
        public string CMTChuSoHuu { get; set; }
        public string DiaChiChuSoHuu { get; set; }
        public string DienThoaiChuSoHuu { get; set; }
        public string MailChuSoHuu { get; set; }
        public string GioiTinhChuSoHuu { get; set; }
        public string TenChuBan { get; set; }
        public string CMTChuBan { get; set; }
        public string DiaChiChuBan { get; set; }
        public string DienThoaiChuBan { get; set; }
        public string GioiTinhChuBan { get; set; }
        public Nullable<int> IDChuDauTu { get; set; }
        public string TenChuDauTu { get; set; }
        public string DiaChiChuDauTu { get; set; }
        public string SoDKKDChuDauTu { get; set; }
        public string DienThoaiChuDauTu { get; set; }
        public string TenDuAn { get; set; }
        public Nullable<int> IDDuAn { get; set; }
        public string GhiChu { get; set; }
        public string UserName { get; set; }
        public string CanHoSo { get; set; }
        public Nullable<int> IDCanHo { get; set; }
        public Nullable<int> IDNha { get; set; }
        public string TenChungCu { get; set; }
        public string TangSo { get; set; }
        public Nullable<bool> HoSoChuDauTuNop { get; set; }
        public Nullable<long> IDHoSoChuDauTu { get; set; }
        public Nullable<int> SoLuongHoSoNop { get; set; }
        public string SoPhatHanh { get; set; }
        public string UserNameNhanHoSo { get; set; }
        public Nullable<int> IDTinhTrangHienTai { get; set; }
        public string UserNameHienTai { get; set; }
        public string DM_TinhTrang { get; set; }
        public Nullable<int> IDDM_TinhTrang { get; set; }
        public string SoPhieuChuyen { get; set; }
        public Nullable<int> IDDM_ChiNhanh { get; set; }
        public string SoTBT { get; set; }
        public Nullable<bool> DaTraTBT { get; set; }
        public string NgayTraTBT { get; set; }
        public string NguoiNhanTBT { get; set; }
        public Nullable<int> SoLuongHoSoTraTBT { get; set; }
        public string UserNameTraTBT { get; set; }
        public string SoPhatHanhGCN { get; set; }
        public Nullable<System.DateTime> NgayPhatHanhGCN { get; set; }
        public string MaVach { get; set; }
        public string SoVaoSoCapGCN { get; set; }
        public Nullable<System.DateTime> NgayTraGCN { get; set; }
        public Nullable<bool> DaTraGCN { get; set; }
        public string NguoiNhanGCN { get; set; }
        public Nullable<int> SoLuongGCNTra { get; set; }
        public string UserNameTraGCN { get; set; }
        public string GhiChuTraKetQua { get; set; }
        public Nullable<System.DateTime> NgayTraHoSo { get; set; }
        public Nullable<bool> DaTraHoSo { get; set; }
        public string NguoiNhanHoSo { get; set; }
        public Nullable<int> SoLuongHoSoTra { get; set; }
        public string UserNameTraHoSo { get; set; }
        public Nullable<bool> DaNopThue { get; set; }
        public Nullable<System.DateTime> NgayNhanBienLaiThue { get; set; }
        public Nullable<bool> DaCoTBT { get; set; }
        public Nullable<bool> DaCoGCN { get; set; }
        public Nullable<int> IDDM_PhongBan { get; set; }
        public string DM_PhongBan { get; set; }
        public string UserNameThuLy { get; set; }
        public Nullable<int> SoLuongTBTVe { get; set; }
        public Nullable<int> SoLuongGCNVe { get; set; }
        public Nullable<bool> HoSoRut { get; set; }
        public string NgayTBTVe { get; set; }
        public string NgayGCNVe { get; set; }
        public Nullable<System.DateTime> NgayCoGCN { get; set; }
        public Nullable<bool> CoYCBS { get; set; }
        public Nullable<System.DateTime> NgayYCBS { get; set; }
        public Nullable<bool> DaBSHS { get; set; }
        public Nullable<System.DateTime> NgayBSHS { get; set; }
        public Nullable<int> SoNgayLamCongVan { get; set; }
        public Nullable<System.DateTime> NgayHenTraCongVan { get; set; }
        public Nullable<bool> CoCongVan { get; set; }
        public Nullable<System.DateTime> NgayCoCongVan { get; set; }
        public Nullable<bool> DaTraCongVan { get; set; }
        public Nullable<System.DateTime> NgayTraCongVan { get; set; }
        public Nullable<bool> DaNopHoSoLan2 { get; set; }
        public Nullable<System.DateTime> NgayNopHoSoLan2 { get; set; }
        public Nullable<System.DateTime> NgayCoTBT { get; set; }
        public Nullable<int> SoLuongHSCon { get; set; }
        public Nullable<bool> NhanLuuTru { get; set; }
        public Nullable<System.DateTime> NgayNhanLuuTru { get; set; }
        public string UserNameCreate { get; set; }
        public Nullable<System.DateTime> NgayCreate { get; set; }
        public string NQ { get; set; }
        public string MaCuaSoTNMT { get; set; }
        public string YKienGiaiQuyet { get; set; }
        public Nullable<bool> DaBanGiaoHoSo { get; set; }
        public Nullable<System.DateTime> NgayBanGiao { get; set; }
        public Nullable<bool> DangChuyenThue { get; set; }
        public Nullable<System.DateTime> NgayChuyenThue { get; set; }
        public Nullable<bool> DangTrinhSo { get; set; }
        public Nullable<System.DateTime> NgayTrinhSo { get; set; }
        public Nullable<bool> CoPhaiNopThue { get; set; }
    }
}
