//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BK_VPDKDatDai
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUAN_LY_DAT_DAIEntities : DbContext
    {
        public QUAN_LY_DAT_DAIEntities()
            : base("name=QUAN_LY_DAT_DAIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DM_TIEU_DE> DM_TIEU_DE { get; set; }
        public DbSet<DM_USER> DM_USER { get; set; }
    }
}
